// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMwtgmw766lqbZ6aAsazUQlcnGwm9yGGs',
    appId: '1:637579177640:web:c0d94934cf63683151dc9d',
    messagingSenderId: '637579177640',
    projectId: 'ytsync-a548b',
    authDomain: 'ytsync-a548b.firebaseapp.com',
    storageBucket: 'ytsync-a548b.firebasestorage.app',
    measurementId: 'G-KXYJ8DGB0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBdVJxND3mwJDljWy7i-ACAbSh5HN_134',
    appId: '1:637579177640:android:dc215438e2538e6a51dc9d',
    messagingSenderId: '637579177640',
    projectId: 'ytsync-a548b',
    storageBucket: 'ytsync-a548b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv2FaF9w1ozfcsfD_7Yg2HWW6cuqRDrrU',
    appId: '1:637579177640:ios:186a08a785fab6bb51dc9d',
    messagingSenderId: '637579177640',
    projectId: 'ytsync-a548b',
    storageBucket: 'ytsync-a548b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMwtgmw766lqbZ6aAsazUQlcnGwm9yGGs',
    appId: '1:637579177640:web:09e945d45e19356751dc9d',
    messagingSenderId: '637579177640',
    projectId: 'ytsync-a548b',
    authDomain: 'ytsync-a548b.firebaseapp.com',
    storageBucket: 'ytsync-a548b.firebasestorage.app',
    measurementId: 'G-R3RP66MCTW',
  );

}